# Generated by Django 5.0.1 on 2024-01-26 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retailer', models.CharField(max_length=64)),
                ('purchaseDate', models.DateField()),
                ('purchaseTime', models.TimeField()),
                ('total', models.FloatField()),
                ('points', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortDescription', models.CharField(max_length=256)),
                ('price', models.FloatField()),
                ('receiptId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipts.receipt')),
            ],
        ),
    ]
